#!/bin/bash

if [ "${1}" == "ShowingImage" ]
then
	make ShowingImage
	out/ShowingImage assets/stuff.jpg
fi

if [ "${1}" == "PlayingVideo" ]
then
	make PlayingVideo
	out/PlayingVideo assets/test.avi
fi

if [ "${1}" == "GaussianSmoothening" ]
then
	make GaussianSmoothening
	out/GaussianSmoothening assets/stuff.jpg
fi
